# set -x
# # export VLLM_ATTENTION_BACKEND=XFORMERS
# export CUDA_VISIBLE_DEVICES=0,1
# export PYTHONPATH=/ytech_m2v_hdd/jianghaonan03/code/VR/verl/flash-attention:$PYTHONPATH

# ENGINE=${1:-vllm}

# python3 -m verl.trainer.main_ppo \
#     algorithm.adv_estimator=grpo \
#     algorithm.use_kl_in_reward=False \
#     data.train_files="/ytech_m2v_hdd/jianghaonan03/data/Think-with-Image/openai/gsm8k/train.parquet" \
#     data.val_files="/ytech_m2v_hdd/jianghaonan03/data/Think-with-Image/openai/gsm8k/test.parquet" \
#     data.train_batch_size=8 \
#     data.val_batch_size=1 \
#     data.max_prompt_length=1024 \
#     data.max_response_length=2048 \
#     data.filter_overlong_prompts=True \
#     data.truncation='error' \
#     data.shuffle=True \
#     data.image_key=images \
#     actor_rollout_ref.model.path="/ytech_m2v_hdd/jianghaonan03/model/Qwen/Qwen3-VL-8B-Instruct" \
#     actor_rollout_ref.model.use_shm=False \
#     actor_rollout_ref.model.enable_gradient_checkpointing=True \
#     actor_rollout_ref.model.use_remove_padding=True \
#     actor_rollout_ref.model.lora_rank=32 \
#     actor_rollout_ref.model.lora_alpha=16 \
#     actor_rollout_ref.model.target_modules=all-linear \
#     actor_rollout_ref.model.exclude_modules='.*visual.*' \
#     actor_rollout_ref.actor.optim.lr=3e-6 \
#     actor_rollout_ref.actor.ppo_mini_batch_size=4 \
#     actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
#     actor_rollout_ref.actor.use_kl_loss=True \
#     actor_rollout_ref.actor.kl_loss_coef=0.01 \
#     actor_rollout_ref.actor.kl_loss_type=low_var_kl \
#     actor_rollout_ref.actor.entropy_coeff=0 \
#     actor_rollout_ref.actor.strategy=fsdp \
#     actor_rollout_ref.actor.fsdp_config.param_offload=False \
#     actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
#     actor_rollout_ref.actor.fsdp_config.model_dtype=bf16 \
#     actor_rollout_ref.actor.fsdp_config.use_orig_params=True \
#     actor_rollout_ref.actor.use_torch_compile=False \
#     actor_rollout_ref.rollout.name=$ENGINE \
#     actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
#     actor_rollout_ref.rollout.gpu_memory_utilization=0.45 \
#     actor_rollout_ref.rollout.max_num_seqs=8 \
#     actor_rollout_ref.rollout.max_model_len=2048 \
#     actor_rollout_ref.rollout.max_num_batched_tokens=2048 \
#     actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
#     actor_rollout_ref.rollout.enable_chunked_prefill=False \
#     actor_rollout_ref.rollout.load_format=safetensors \
#     actor_rollout_ref.rollout.enforce_eager=False \
#     actor_rollout_ref.rollout.free_cache_engine=False \
#     actor_rollout_ref.rollout.n=4 \
#     +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
#     actor_rollout_ref.ref.strategy=fsdp \
#     actor_rollout_ref.ref.fsdp_config.param_offload=True \
#     actor_rollout_ref.ref.fsdp_config.model_dtype=bf16 \
#     actor_rollout_ref.ref.fsdp_config.use_orig_params=True \
#     actor_rollout_ref.ref.use_torch_compile=False \
#     actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=10 \
#     trainer.critic_warmup=0 \
#     trainer.n_gpus_per_node=2 \
#     trainer.nnodes=1 \
#     trainer.logger='["console", "wandb"]' \
#     trainer.project_name='verl_grpo_example_gsm8k' \
#     trainer.experiment_name='qwen3_vl_8b_function_rm' \
#     trainer.save_freq=1 \
#     trainer.test_freq=1 \
#     trainer.total_epochs=2


set -x
# export VLLM_ATTENTION_BACKEND=XFORMERS
export CUDA_VISIBLE_DEVICES=0,1
export PYTHONPATH=/ytech_m2v_hdd/jianghaonan03/code/VR/verl/flash-attention:$PYTHONPATH

ENGINE=${1:-vllm}

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    algorithm.use_kl_in_reward=False \
    data.train_files="/ytech_m2v_hdd/jianghaonan03/data/Think-with-Image/openai/gsm8k/train.parquet" \
    data.val_files="/ytech_m2v_hdd/jianghaonan03/data/Think-with-Image/openai/gsm8k/test.parquet" \
    data.train_batch_size=8 \
    data.val_batch_size=1 \
    data.max_prompt_length=1024 \
    data.max_response_length=2048 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=True \
    data.image_key=images \
    actor_rollout_ref.model.path="/ytech_m2v_hdd/jianghaonan03/model/Qwen/Qwen3-VL-8B-Instruct" \
    actor_rollout_ref.model.use_shm=False \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=3e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.01 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.actor.fsdp_config.model_dtype=bf16 \
    actor_rollout_ref.actor.fsdp_config.use_orig_params=True \
    actor_rollout_ref.actor.use_torch_compile=False \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.45 \
    actor_rollout_ref.rollout.max_num_seqs=8 \
    actor_rollout_ref.rollout.max_model_len=2048 \
    actor_rollout_ref.rollout.max_num_batched_tokens=2048 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.n=4 \
    +actor_rollout_ref.rollout.engine_kwargs.vllm.disable_mm_preprocessor_cache=True \
    actor_rollout_ref.ref.strategy=fsdp \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.fsdp_config.model_dtype=bf16 \
    actor_rollout_ref.ref.fsdp_config.use_orig_params=True \
    actor_rollout_ref.ref.use_torch_compile=False \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=10 \
    trainer.critic_warmup=0 \
    trainer.n_gpus_per_node=2 \
    trainer.nnodes=1 \
    trainer.logger='["console", "wandb"]' \
    trainer.project_name='verl_grpo_example_gsm8k' \
    trainer.experiment_name='qwen3_vl_8b_function_rm' \
    trainer.save_freq=1 \
    trainer.test_freq=1 \
    trainer.total_epochs=2

