train_datasets:
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_caption_retrieval_1.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.27
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_caption_retrieval_2.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.27
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_caption_retrieval_3.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.27
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_caption_retrieval_4.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.27
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_caption_retrieval_5.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.27
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_qa_1.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 4.38
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_qa_2.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 4.38
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_qa_3.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 4.38
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_qa_4.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 4.38
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_qa_5.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 4.38
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_video_retrieval_1.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.76
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_video_retrieval_2.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.76
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_video_retrieval_3.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.76
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_video_retrieval_4.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.76
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: llavahound
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-video-filter
  json_file: llavahound_video_retrieval_5.json
  root_path: ../../data/VR/data/vlm2vec_train/
  weight: 5.76
  max_samples: null
  video_frame_rate: 2
  max_frames: 8
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: A-OKVQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.26
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: ChartQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.35
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: CIRR.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.43
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: DocVQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.84
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: ImageNet_1K.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 2.25
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: InfographicsVQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.31
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: MSCOCO_i2t.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 2.58
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: MSCOCO.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 3.78
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: MSCOCO_t2i.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 2.32
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: NIGHTS.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.23
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: OK-VQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.25
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: SUN397.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.22
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: vidore_samples_1.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 5.0
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: vidore_samples_2.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 5.0
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: VisDial.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 3.75
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: visrag_samples_1.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 6.0
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: visrag_samples_2.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 6.0
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: Visual7W.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 1.68
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: VisualNews_i2t.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 2.91
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: VisualNews_t2i.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 3.49
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true
- type: mmeb
  path: ../../data/VR/data/vlm2vec_train/MMEB-train-sample-cot-filter
  json_file: WebQA.json
  root_path: ../../data/VR/data/vlm2vec_train/MMEB-train/
  weight: 0.23
  max_samples: null
  concat_query_cot: true
  concat_target_cot: true